sudo: required
dist: trusty

cache:
  directories:
  - $HOME/.gradle

language: java
jdk:
  - openjdk8
  - oraclejdk8

git:
  submodules: false
before_install: scripts/travis-initialize-submodules

script: ./gradlew build

notifications:
  email: false
