name: Java CI with Gradle

on:
  push:
    branches-ignore: [ 'api-*' ]
    tags-ignore: ["**"]
  pull_request:
    branches-ignore: [ stable-7 ]

jobs:
  build:
    uses: ./.github/workflows/common-run-build.yaml
    secrets: inherit
  integrationTest:
    needs: build
    uses: ./.github/workflows/common-integration-test.yaml
    secrets: inherit